### ISSUE TITLE
JSON Formatting issue

### ISSUE THREAD

**Issue by AcesGamingUK** [SimpleBroadcast/SimpleBroadcast#27]
every now and then will see a JSON format warning,
now just to be clear its not just 1 broadcast, its random ones every time,
they are all correct and have all worked ,
it just randomized

here is error 
http://hastebin.com/zetumipepi.avrasm

**Comment by ghost** [comment]
Hello,

could you please attach your config files here? On which Minecraft version does your server run? Are you using BarAPI?

Kind regards,
KingDome24

**Comment by AcesGamingUK** [comment]
http://hastebin.com/eyehazuquk.md

as i said generally they all work, just now and then it will randomly show up as a JSON error in chat

using latest 1.8.8 spigot
no bar api
