### ISSUE TITLE
JSON not showing the Prefix

### ISSUE THREAD

**Issue by MrCrispis** [SimpleBroadcast/SimpleBroadcast#28]
Hello, I'll go straight forward to the problem.

When adding JSON messages, the prefix is not showing up.

Here is the config.yml:
http://pastebin.com/zutA4hid

As you can see, I have the prefix enabled.

Please fix it! :+1:

**Comment by ghost** [comment]
Hello,

this is more or less an intended behaviour of v1.X.
This will get fixed in v2.X.

Kind regards,
KingDome24
