### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Jake17689** [SimpleBroadcast/SimpleBroadcast#6]
Why doesn't it change?!?!?!? I have went into the configs and changed the messages and I put ' in front and back, saved it, restarted my server and it keeps saying those default things in chat! Help!

**Comment by timvango** [comment]
In your config Enabled is set to false.

**Comment by KingDome24** [comment]
@timvango You're right. I've totally overlooked that. :)

**Comment by KingDome24** [comment]
If the problem still exists, please create a new ticket with the required information.
