### ISSUE TITLE
Colors formats

### ISSUE THREAD

**Issue by kaptainz12** [SimpleBroadcast/SimpleBroadcast#7]
Hello!

First of all thanks for making this amazing plugin & taking care of it more than enough!
My issue:

After updating the plugin today, I realised that the colour formats aren't working on broadcasts, Idk for what reason, it was just working perfectly before updating it, but after I update it, it just stopped supporting colour formats! 
Edit: When I use /simplebroadcast raw &6Hi / it works, but the Auto Broadcasts doesn't, they just appear as &6..
Thanks again!

**Comment by KingDome24** [comment]
Hello,

I'm unfortunately not able to reproduce your problem.
Could you please upload your config on pastebin.com and share the link here?

KingDome24

**Comment by kaptainz12** [comment]
Sure, but I don't think it has to do something with the Config..
but here is the link http://pastebin.com/uhihgP3v
Thanks again for this plugin :+1:  !

**Comment by kaptainz12** [comment]
Maybe cause Im using spigot 1.7 - 1.8 ?

**Comment by angrybirds85** [comment]
I too am having this problem with the latest Spigot, the auto broadcasts are not showing colours but they show &1Message, and if I type /simplebroadcast now 1 to show the first message it does show the colours

**Comment by KingDome24** [comment]
Hello,

thanks for your report and also for your config file.
I was able to reproduce the problem and fixed it (fix will be available in v1.8.1).

For now: Please turn of "randomizemessages" (set it to `false`) to be able to see colours in your messages.

Kind regards,
KingDome24

**Comment by kaptainz12** [comment]
Thanks a lot ☺!

**Comment by angrybirds85** [comment]
Any estimate on when the 1.8.1 version is coming out?

**Comment by KingDome24** [comment]
Hello,

it won't take too long until the new version gets released.
Probably within the next 3 days. :)

KingDome24

**Comment by KingDome24** [comment]
@kaptainz12 
@angrybirds85 
See https://github.com/SimpleBroadcast/SimpleBroadcast/releases/tag/v1.8.1

**Comment by kaptainz12** [comment]
Ok I'll be testing it now 😊!
